defaults:
  # Train Script
  log_dir: results
  seed: 0
  task: cartpole.balance
  time_limit: 1000
  action_repeat: 2
  steps: 1e6
  training_steps_per_epoch: 2.5e4
  evaluation_steps_per_epoch: 1e4
  prefill: 5000
  update_interval: 1000
  update_steps: 100
  replay: { capacity: 1000, batch_size: 50, sequence_length: 50 }
  jit: True
  render_episodes: 1
  evaluate_model: True
  precision: 16
  initialization: glorot

  # World Model
  rssm: { hidden_size: 200, deterministic_size: 200, stochastic_size: 30 }
  model_opt: { lr: 6e-4, eps: 1e-7, clip: 100 }
  encoder: { depth: 32, kernels: [4, 4, 4, 4], output_dim: 1024 }
  decoder: { depth: 32, kernels: [5, 5, 6, 6] }
  reward: { output_sizes: [230, 400, 400, 400, 1] }
  terminal: { output_sizes: [230, 400, 400, 400, 1] }
  free_nats: 3.0
  kl_scale: 1.0

  # Actor-Critic
  actor:
    {
      output_sizes: [400, 400, 400, 400],
      min_stddev: 1e-4,
      lr: 8e-5,
      eps: 1e-7,
      clip: 100,
    }
  critic: { output_sizes: [400, 400, 400], lr: 8e-5, eps: 1e-7, clip: 100 }
  discount: 0.99
  lambda_: 0.95
  imag_horizon: 15

debug:
  jit: False
  time_limit: 100
  training_steps_per_epoch: 200
  evaluation_steps_per_epoch: 0
  prefill: 100
  train_every: 100
  update_steps: 2
  render_episodes: 0
  replay: { capacity: 10, batch: 10, sequence_length: 8 }

envs:
  [
    "AirRaidNoFrameskip-v4",
    "AlienNoFrameskip-v4",
    "AmidarNoFrameskip-v4",
    "AssaultNoFrameskip-v4",
    "AsterixNoFrameskip-v4",
    "AsteroidsNoFrameskip-v4",
    "AtlantisNoFrameskip-v4",
    "BankHeistNoFrameskip-v4",
    "BattleZoneNoFrameskip-v4",
    "BeamRiderNoFrameskip-v4",
    "BerzerkNoFrameskip-v4",
    "BowlingNoFrameskip-v4",
    "BoxingNoFrameskip-v4",
    "BreakoutNoFrameskip-v4",
    "CarnivalNoFrameskip-v4",
    "CentipedeNoFrameskip-v4",
    "ChopperCommandNoFrameskip-v4",
    "CrazyClimberNoFrameskip-v4",
    "DefenderNoFrameskip-v4",
    "DemonAttackNoFrameskip-v4",
    "DoubleDunkNoFrameskip-v4",
    "ElevatorActionNoFrameskip-v4",
    "EnduroNoFrameskip-v4",
    "FishingDerbyNoFrameskip-v4",
    "FreewayNoFrameskip-v4",
    "FrostbiteNoFrameskip-v4",
    "GopherNoFrameskip-v4",
    "GravitarNoFrameskip-v4",
    "HeroNoFrameskip-v4",
    "IceHockeyNoFrameskip-v4",
    "JamesbondNoFrameskip-v4",
    "JourneyEscapeNoFrameskip-v4",
    "KangerooNoFrameskip-v4",
    "KrullNoFrameskip-v4",
    "KungFuMasterNoFrameskip-v4",
    "MontezumaRevengeNoFrameskip-v4",
    "MsPacmanNoFrameskip-v4",
    "NameThisGameNoFrameskip-v4",
    "PhoenixNoFrameskip-v4",
    "PitfallNoFrameskip-v4",
    "PongNoFrameskip-v4",
    "PooyanNoFrameskip-v4",
    "PrivateEyeNoFrameskip-v4",
    "QbertNoFrameskip-v4",
    "RiverraidNoFrameskip-v4",
    "RoadRunnerNoFrameskip-v4",
    "RobotTankNoFrameskip-v4",
    "SeaquestNoFrameskip-v4",
    "SkiingNoFrameskip-v4",
    "SolarisNoFrameskip-v4",
    "SpaceInvadersNoFrameskip-v4",
    "StarGunnerNoFrameskip-v4",
    "TennisNoFrameskip-v4",
    "TimePilotNoFrameskip-v4",
    "TutankhamNoFrameskip-v4",
    "UpNDownNoFrameskip-v4",
    "VentureNoFrameskip-v4",
    "VideoPinballNoFrameskip-v4",
    "WizardOfWorNoFrameskip-v4",
    "YarsRevengeNoFrameskip-v4",
    "ZaxxonNoFrameskip-v4",
    "AdventureNoFrameskip-v4",
  ]
